"""add UserCreate

Revision ID: 45c709845616
Revises: e983e2e22e38
Create Date: 2024-04-22 01:33:18.584834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c709845616'
down_revision = 'e983e2e22e38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
