"""i

Revision ID: 9a85a68f4d60
Revises: 45c709845616
Create Date: 2024-04-24 00:20:26.725243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a85a68f4d60'
down_revision = '45c709845616'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_tag_user', 'contacts', ['id', 'user_id'])
    op.drop_constraint('contacts_user_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_user_id_fkey', 'contacts', 'users', ['user_id'], ['id'])
    op.drop_constraint('unique_tag_user', 'contacts', type_='unique')
    # ### end Alembic commands ###
